package app.serenada.callui

enum class SerenadaString {
    CallLocalCameraOff,
    CallCameraOff,
    CallVideoOff,
    CallWaitingShort,
    CallReconnecting,
    CallTakingLongerThanUsual,
    CallWaitingOverlay,
    CallShareLinkChooser,
    CallShareInvitation,
    CallInviteToRoom,
    CallQrCode,
    CallToggleFlashlight,
    CallToggleVideoFit,
    CallTakeSnapshot,
    FrontlineYou,
    FrontlineWaiting,
    FrontlineVideo,
    FrontlineVideoOn,
    FrontlineMute,
    FrontlineMore,
    FrontlineEnd,
    FrontlineFlipCamera,
    FrontlineStopScreenShare,
    FrontlineShareScreen,
    FrontlineReturnToCamera,
    FrontlineShowYourPhone,
    FrontlineInviteSubtitle,
    FrontlineShareLinkSubtitle,
    FrontlineClose,
}

val serenadaDefaultStrings: Map<SerenadaString, String> = mapOf(
    SerenadaString.CallLocalCameraOff to "Your camera is off",
    SerenadaString.CallCameraOff to "Camera off",
    SerenadaString.CallVideoOff to "Video off",
    SerenadaString.CallWaitingShort to "Waiting...",
    SerenadaString.CallReconnecting to "Reconnecting...",
    SerenadaString.CallTakingLongerThanUsual to "Taking longer than usual...",
    SerenadaString.CallWaitingOverlay to "Waiting for someone to join...",
    SerenadaString.CallShareLinkChooser to "Share call link",
    SerenadaString.CallShareInvitation to "Share invitation",
    SerenadaString.CallInviteToRoom to "Invite to call",
    SerenadaString.CallQrCode to "QR code",
    SerenadaString.CallToggleFlashlight to "Toggle flashlight",
    SerenadaString.CallToggleVideoFit to "Toggle video fit",
    SerenadaString.CallTakeSnapshot to "Take photo",
    SerenadaString.FrontlineYou to "You",
    SerenadaString.FrontlineWaiting to "Waiting",
    SerenadaString.FrontlineVideo to "VIDEO",
    SerenadaString.FrontlineVideoOn to "VIDEO ON",
    SerenadaString.FrontlineMute to "MUTE",
    SerenadaString.FrontlineMore to "MORE",
    SerenadaString.FrontlineEnd to "END",
    SerenadaString.FrontlineFlipCamera to "Flip camera",
    SerenadaString.FrontlineStopScreenShare to "Stop screen share",
    SerenadaString.FrontlineShareScreen to "Share screen",
    SerenadaString.FrontlineReturnToCamera to "Return to camera",
    SerenadaString.FrontlineShowYourPhone to "Show your phone",
    SerenadaString.FrontlineInviteSubtitle to "Bring in another teammate",
    SerenadaString.FrontlineShareLinkSubtitle to "Send the call link",
    SerenadaString.FrontlineClose to "Close",
)

fun resolveString(key: SerenadaString, overrides: Map<SerenadaString, String>?): String {
    return overrides?.get(key) ?: serenadaDefaultStrings[key] ?: key.name
}
